name: Performance Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  performance-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: gopi -f config.json --test-perf
      - run: gopi -f config.json --test-load-data
      - run: gopi -f config.json --test-load-user
